### PR TITLE
Added an intro section

### PR DESCRIPTION
**Pull request by Anirban780**
This intro section attracts the user and gives them a heartful message about the website with animation effects

### CODE REVIEW

**Comment by ayush-848** [comment]
@Anirban780 resolve the conflicts

**Comment by Anirban780** [comment]
vercel deployment has failed, please check this issue and ask me if you need helping hand

**Comment by ayush-848** [comment]
> vercel deployment has failed, please check this issue and ask me if you need helping hand

resolve the conflicts

**Comment by ayush-848** [comment]
@Anirban780 some deployment error are present. Fix them

**Pull request closed without merging**
